# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# AndroidX support
android.useAndroidX=true

# Performance improvements
android.dependency.excludeLibraryComponentsFromConstraints=true

# Other settings
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.disallowKotlinSourceSets=false
